# Simple docker-compose.yml
# You can change your port or volume location

version: '3.3'

services:
  app:
    image: filebrowser/filebrowser:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /:/srv
      - /opt/filebrowser/database/filebrowser.db:/database/filebrowser.db
      - /opt/filebrowser/config:/config
    ports:
      - 8081:80  # <Host Port>:<Container Port>
    restart: unless-stopped