---
version: "2.1"
services:
  resilio-sync-new:
    image: lscr.io/linuxserver/resilio-sync:latest
    container_name: resilio-sync-new
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /opt/resilio-sync/config:/config
      - /opt/resilio-sync/downloads:/downloads
      - /opt/resilio-sync/data:/sync
      - /opt:/sync/ubuntu-lenovo-server-backup
    ports:
      - 8888:8888
      - 55555:55555
    restart: unless-stopped
