---
version: "2.1"
services:
  app:
    image: lscr.io/linuxserver/unifi-controller:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - MEM_LIMIT=1024 #optional
      - MEM_STARTUP=1024 #optional
    volumes:
      - /opt/unifi-controller/config:/config
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    restart: unless-stopped
